
POST http://localhost:3000/user/register
Content-Type: application/json

{
    "first_name": "Anna",
    "last_name": "Lora",
    "email": "annalora@t.com",
    "password": "1234"
}

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "annalora@t.com",
    "password": "1234"
}

###

GET http://localhost:3000/user/doSomeWork
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWIyZThjZGIzNzlmOTI3OTgyODM0ZGIiLCJpYXQiOjE2MzkxMTUwNjksImV4cCI6MTYzOTExNTA5OX0.2BZu1eH7Ahmm4wi6AyofR13AIbq82gVH2UrXUv5jQ2M
Content-Type: application/json

###
POST http://localhost:3000/user/refreshToken
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWIyZThjZGIzNzlmOTI3OTgyODM0ZGIiLCJpYXQiOjE2MzkxMTUwNjksImV4cCI6MTY0MTcwNzA2OX0.XzBnjwV3tZZGCEOLaYK2mNRwt3Lr4KeITdC_4O3-Nus"
}


###

POST http://localhost:3000/user/logout
Content-Type: application/json

{
    "userId": "61b2e8cdb379f927982834db"
}
