
POST http://localhost:3000/user/register
Content-Type: application/json

{
    "first_name": "Sara",
    "last_name": "Gwen",
    "email": "saragwen@t.com",
    "password": "1234"
}

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "saragwen@t.com",
    "password": "1234"
}

###

GET http://localhost:3000/user/doSomeWork
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWFkYjE5NTRhYjQ4YzNhNGNjNDY4YzIiLCJpYXQiOjE2Mzg5NTU5NDcsImV4cCI6MTYzODk1NTk3N30.1mi5J-muZPKcvm4sGn9lplcSGeqr5Em51CeJh4hHKVQ
Content-Type: application/json

###
POST http://localhost:3000/user/refreshToken
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWFkYjE5NTRhYjQ4YzNhNGNjNDY4YzIiLCJpYXQiOjE2Mzg5NTU5NDcsImV4cCI6MTY0MTU0Nzk0N30.aabOdAlLM9RzlwL3AmDs9OSdDoh9FtT-6NkyObItFgI"
}


###

POST http://localhost:3000/user/logout
Content-Type: application/json

{
    "userId": "61adb1954ab48c3a4cc468c2"
}
